root: true
extends:
  - prettier
parserOptions:
  ecmaVersion: 13
env:
  node: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
